### ISSUE TITLE
Link to read docs broken.

### ISSUE THREAD

**Issue by mkpage** [chekos/pypums#131]
The link to read the docs is broken.

**Comment by chekos** [comment]
thanks @mkpage, it seems that readthedocs.org is down.

**Comment by mkpage** [comment]
Thanks.

Max Krueger, WELL AP, LEED AP BD+C
Page
Data Analyst
mkrueger@pagethink.com <mailto:mkrueger@pagethink.com>
720 390 3047

Our highest priority is the health, safety and well-being of our employees, their families, our clients, our communities, and those with whom we work. Even working remotely, our full resources are available to support you.
